const modelName = 'StudentProfile';
const folder = 'academic/studentProfile';
const rootFolder = `app/modules/${folder}`;

module.exports = {
  modelName,
  folder,
  rootFolder,
  apiUrl: '/academic/student-profiles',
  model: [
    {
      field: 'first_name',
      type: 'string',
      required: true,
      editable: true,
    },
    { field: 'nationality', type: 'string', editable: true },
    { field: 'address_city', type: 'string', editable: true },
    { field: 'address_sub_city', type: 'string', editable: true },
    { field: 'address_woreda', type: 'string', editable: true },
    { field: 'house_number', type: 'string', editable: true },
    { field: 'student_phone_number', type: 'string', editable: true },
    { field: 'other_health_status', type: 'string', editable: true },
    { field: 'previous_school_name', type: 'string', editable: true },
    { field: 'previous_school_city', type: 'string', editable: true },
    { field: 'previous_school_sub_city', type: 'string', editable: true },
    { field: 'previous_school_woreda', type: 'string', editable: true },
    { field: 'school_leave_other', type: 'string', editable: true },
    { field: 'entry_class', type: 'string', editable: true },
    { field: 'parent_name', type: 'string', editable: true },
    { field: 'occupation', type: 'string', editable: true },
    { field: 'work_place', type: 'string', editable: true },
    { field: 'parent_phone_number', type: 'string', editable: true },
    { field: 'student_living_with', type: 'string', editable: true },
    { field: 'date_of_birth', type: 'date', editable: true },
    { field: 'student_photo', type: 'string', subtype: 'text', editable: true },
    { field: 'parent_photo', type: 'string', subtype: 'text', editable: true },
    { field: 'emergencies', type: 'string', subtype: 'text', editable: true },
    {
      field: 'student_id',
      type: 'string',
      subtype: 'uuid',
      required: true,
      editable: true,
      foreign: {
        column: 'id',
        table: 'students',
      },
    },
    { field: 'health_status', type: 'enum', editable: true },
    { field: 'previous_school_leave_reason', type: 'enum', editable: true },
    { field: 'father_condition', type: 'enum', editable: true },
    { field: 'mother_condition', type: 'enum', editable: true },
  ],
  routes: {
    prefix: 'student-profiles',
    map: [
      {
        method: 'post',
        path: '/',
        handleFunction: 'store',
        permission: 'add-student-profile',
      },
      {
        method: 'post',
        path: '/search',
        handleFunction: 'search',
        permission: 'add-student-profile',
      },
      {
        method: 'get',
        path: '/',
        handleFunction: 'index',
        permission: 'view-student-profile',
      },
      {
        method: 'get',
        path: '/paginate',
        handleFunction: 'paginate',
        permission: 'view-student-profile',
      },
      {
        method: 'get',
        path: '/:id',
        handleFunction: 'show',
        permission: 'view-student-profile',
      },
      {
        method: 'patch',
        path: '/:id',
        handleFunction: 'update',
        permission: 'edit-student-profile',
      },
      {
        method: 'delete',
        path: '/:id',
        handleFunction: 'delete',
        permission: 'remove-student-profile',
      },
      {
        method: 'post',
        path: '/show/:id',
        handleFunction: 'showDetail',
        permission: 'view-student-profile',
      },
    ],
  },
  roles: [
    'add-student-profile',
    'edit-student-profile',
    'remove-student-profile',
    'view-student-profile',
  ],
};
